### ISSUE TITLE
[공통] GNB 컴포넌트

### ISSUE THREAD

**Issue by joonyoungchoi0801** [sihyonn/sprint-part2-rollingProject#1]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
![gnb](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/a845f1fb-8104-4e3f-9b3c-9e475c457e95)

## 📌 ToDo
- [x] 로고' 버튼을 클릭하면 / 페이지로 이동합니다. 
- [x] '롤링 페이퍼 만들기' 버튼을 클릭하면 /post 페이지로 이동합니다.
- [x] Tablet에서 상단 네비게이션은 좌우 여백은 24px로 고정하고 '로고'와 '롤링 페이퍼 만들기' 버튼의 간격이 줄어들거나 커집니다.

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
전체화면일때
<br>
![gnb완성](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/df557246-2f0f-456b-b394-cf433c8d7e2a)
<br>
축소화면일때
<br>
![gnb화면 줄였을시](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/07447003-d60d-4913-a261-7e528e4af049)
<br>
fixed구현
<br>
![gnb fixed 확인](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/54345b3a-fb7a-4ad1-b3bd-ef09b211b2a7)

gnb바 아래 내용은 그냥 임시로 만든겁니다!

**Comment by sihyonn** [comment]
굳굳굳! 
준영님 나중에 코드 push 하시면 현재 etc에 있는 완성샷 pr 스크린샷으로 옮겨주시고
템플릿에 있는 문구들은 삭제하셔두 됩니다! 준영님의 내용만 보여주면 될 것 같아욯
