### ISSUE TITLE
[공통] 이모지박스 및 Url 공유 기능 구현

### ISSUE THREAD

**Issue by joonyoungchoi0801** [sihyonn/sprint-part2-rollingProject#13]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
![이모지 리스트](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/e0e0b038-9cf1-4834-ba0e-7f2dcf1e5ce1)

## 📌 ToDo

- [x] 저장된 이모지는 횟수가 많은 순서대로 최대 '8개' 까지 나열해 주세요
- [x] 이모지 추가 드롭다운 디자인은 예시이고, 이와 동일한 기능을 하는 외부 모듈의 디자인을 그대로 사용해도 좋습니다.
- [x] 카카오톡 공유 docs를 참고해 '카카오톡 공유' 기능을 만들어 주세요. (구현 방법이나 공유에 들어갈 메시지는 팀 내에서 논의해 결정해 주세요)

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
만든 컴포넌트
![share badge](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/02ee6aff-0379-4fd7-b0db-1776cf9328c4)
이모지 박스
![뱃지 리스트](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/7e5fa822-42c9-4969-9908-7404ecdbe8a7)
이모지 입력란
![선택한 이모지 data](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/4c9d8be6-913e-4343-b3e7-039085142dcd)
-> 밑에 data도 useState로 state로 저장하게 만들었습니다
카톡공유란 (오늘 회의때 상의해야할 내용입니다)
![카톡 공유](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/efb592d4-b213-413d-b7a5-6a71c8b57b16)
->카톡 공유는 배포해야지만 가능해서 배포하면 정상적으로 작동합니다
url 복사시 나오는 toast
![url 복사시 toast](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/7680de12-60ed-44ec-a634-1a9c8e389126)
share 버튼
![share](https://github.com/sihyonn/sprint-part2-rollingProject/assets/151784621/5226c915-fac0-41e3-9ad7-7b1c408b6e73)

일단 코드는 다 만들었습니다 기능이 너무 많아서 설명은 자고 일어나서 회의때나 pr올리면 하겠습니다
현일님 이모지 뱃지 컴포넌트 다 만들면 코드 수정할 내용 수정 후  push, pr올리겠습니다
