### ISSUE TITLE
[공통] 관계를 알려주는 뱃지 구현

### ISSUE THREAD

**Issue by Dharmaparami** [sihyonn/sprint-part2-rollingProject#2]
## 📌 기능설명
관계를 알려주는 뱃지를 구현하였습니다.

## 📌 ToDo
- [x] 뱃지 안에 쓰인 텍스트를 prop으로 받아서 백그라운드 및 색상 fima 시안에 맞게 변경하기
- [x] '상대와의 관계' 항목은 지인이 기본값으로 선택되어 있습니다.
## 🤔 ETC[선택]
구현한 ui 모습
<img width="166" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/cc565f85-7bc1-46f1-bb6c-6260a5862776">

최상위 컴포넌트에서 삽입된 모습
<img width="756" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/8094ec4a-8436-4d7d-8d2b-e84da80882b0">

props.children 값에 따라 백그라운드와 글씨의 색깔이 바뀌게끔 코딩
<img width="981" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/8e6fd8c3-bb1e-4621-a950-3d4613c18bf5">

++수정사항 (반영완료 시 체크)
- [x] 파일 내에서 작성한 스타일드 컴포넌트를 구분하기 위해 Styled 변수에 객체를 담아 프로퍼티로 사용하기
- [x] 코드 가독성을 위해 switch 문을 제거하고 props, 객체 활용하기
- [x] 기본값을 지인으로 가지게끔 수정완료
<img width="571" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/aa6c48c3-d5be-4165-8290-aa5ed955af2c">

**Comment by sihyonn** [comment]
@Dharmaparami  오 현일님 벌써 뱃지구현완료하시다니..👍🏻
children 따라서 switch문 사용하셔서 배경과 폰트색상 정말 잘 적용해주신거 같아요
여기서 조금 더 중복을 줄여본다면

<img width="412" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/124874266/90b254fa-5f34-4b8e-ad48-0c50c13e01cd">

이런식으로 children에 해당하는 명칭에 background와 color를 객체에 담고,

<img width="647" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/124874266/09222bce-5cbf-4713-89d2-41aa26d0b29a">
이렇게 스타일드 컴포넌트에서 대괄호법으로 객체에 접근해서 사용해주는 방법도 생각해볼 수 있을 것 같네요!!!

**Comment by Dharmaparami** [comment]
@sihyonn 보완할 점 말씀해주셔서 감사합니다! 말씀하신대로 수정해보겠습니다 ㅎㅎ
