### ISSUE TITLE
Main, List, Create, Write 페이지 반응형 레이아웃 구현

### ISSUE THREAD

**Issue by sihyonn** [sihyonn/sprint-part2-rollingProject#41]
## 📌 기능설명
각 페이지에 적용 될 반응형 레이아웃 구현

## 📌 ToDo
- [x] 전체 공통 Layout
- [x] Main, List Layout
- [x] Create, Write Layout

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
