### ISSUE TITLE
landing page 구현

### ISSUE THREAD

**Issue by joonyoungchoi0801** [sihyonn/sprint-part2-rollingProject#51]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!

## 📌 ToDo
- [ ] '구경해보기' 버튼을 클릭하면 /list 페이지로 이동합니다.
- [ ] Tablet에서 화면의 너비가 줄어들거나 커지면 '구경해보기' 버튼의 너비가 줄어들거나 커집니다.
- [ ] Mobile에서 좌우 여백은 24px로 고정합니다

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
