### ISSUE TITLE
PaperViewerPage(2) 페이지 UI 및 요구사항 충족해서 구현

### ISSUE THREAD

**Issue by sihyonn** [sihyonn/sprint-part2-rollingProject#54]
## 📌 기능설명
<img width="682" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/124874266/79f2e05c-9b8e-4b5a-9e25-7c22a340b8fe">
<img width="682" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/124874266/d4964f9f-9803-4b43-8998-f9ca13dfee3c">

## 📌 ToDo
- [ ] 카드 목록은 '최신순'으로 무한 스크롤 방식으로 배치
- [ ] '카드'를 누르면 해당 카드가 확대
- [ ] '+' 버튼을 누르면 /post/{id}/message 로 이동
- [ ] 이미지, 색상 받아서 배경화면 바뀌도록 설정

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
