### ISSUE TITLE
[api] 헤더 관련 api작업

### ISSUE THREAD

**Issue by joonyoungchoi0801** [sihyonn/sprint-part2-rollingProject#61]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
list 페이지 에서 받아오는 id를 통해 data가져와서 header만들기
## 📌 ToDo
- [ ]  get https://rolling-api.vercel.app/4-15/recipients/{id}/
- [ ] post https://rolling-api.vercel.app/4-15/recipients/{recipients_id}/reactions/
- [x] get https://rolling-api.vercel.app/4-15/recipients/{id/messages/
## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
