### ISSUE TITLE
[Fix] 카드 메시지 데이터 개수 조정, 스켈레톤 UI 싱크 맞추기

### ISSUE THREAD

**Issue by sihyonn** [sihyonn/sprint-part2-rollingProject#98]
## 📌 기능설명
카드 메시지에 대한 리팩토링을 진행합니댜_!

## 📌 ToDo
- [x] 무한스크롤 목록 불러올때
  + Viewer : 5, 6, 6, ... 받아올 수 있도록
  + Edit : 6, 6, 6, ... 6단위로 가져오기오기
- [x] 카드 스켈레톤 로더 수정
- [x] 상수들 Object.freeze 처리

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
